version: '3.4'

services:
  app:
    container_name: trident-docker-c
    image: trident-docker-i
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5173:5173